# Cross-validate the NRRD reader of this package against pynrrd and ITK.
#
# The NRRD format has a lot of variants (four encodings, attached or detached data, skip fields, optional
# space information, data file lists), and every one of them is a chance to misread a file silently. The test
# files in 'extra_test_data/nrrd' cover the variants, and each of them comes with a dump of what the reference
# implementations read from it:
#
#   1. pynrrd (which is what Python uses for NRRD, since nibabel has no NRRD support) supplies the array
#      shape, the data type and all values of every file. Reading a file with this package has to reproduce
#      them exactly.
#   2. SimpleITK (ITK itself, the origin of the NRRD format's space information) supplies the geometry, i.e.
#      the origin, the spacing and the direction cosines in ITK's LPS world coordinates. The voxel-to-RAS
#      matrix computed by this package has to describe the same geometry. ITK normalizes a sheared basis,
#      which its image model cannot express, so the file with a shear is only compared against pynrrd.
#   3. Two files cannot be read by pynrrd (the 'data file: LIST' mode, whose file name lines are not header
#      fields, and a whole-file gzip-compressed NRRD file). They are checked structurally instead, by
#      comparing their data against the uncompressed file that holds the same values.
#
# The test data is generated by
#   python3 dev_tools/generate_nrrd_test_data.py generate extra_test_data/nrrd
# which requires pynrrd (pip install pynrrd) and, for the geometry part of the dumps, SimpleITK. Run this
# script with
#   Rscript dev_tools/check_nrrd_conversion.R

script_args <- commandArgs(trailingOnly = FALSE)
script_file <- sub("^--file=", "", script_args[grep("^--file=", script_args)])
repo_root <- if (length(script_file) == 1L) normalizePath(file.path(dirname(script_file), ".."), mustWork = FALSE) else getwd()
if (!file.exists(file.path(repo_root, "DESCRIPTION"))) {
  repo_root <- getwd()
}
devtools::load_all(repo_root, quiet = TRUE)

data_dir <- file.path(repo_root, "extra_test_data", "nrrd")
dump_dir <- file.path(data_dir, "expected")

# The files whose dumps pynrrd cannot provide, see the comment at the top of
# dev_tools/generate_nrrd_test_data.py.
no_oracle_files <- c("vol_datafile_list.nhdr", "vol_u8_raw.nrrd.gz")

string_keys <- c("file", "type", "encoding", "endian", "space")
int_keys <- c("dimension", "num_values")
number_list_keys <- c("sizes", "space_directions", "space_origin", "spacings", "values",
                      "itk_origin", "itk_spacing", "itk_direction")

#' Parse a dump written by the Python generator into a named list.
read_nrrd_dump <- function(path) {
  lines <- readLines(path)
  result <- list(custom = list())
  for (line in lines) {
    space_pos <- regexpr(" ", line, fixed = TRUE)[1L]
    if (space_pos < 1L) {
      next
    }
    key <- substr(line, 1L, space_pos - 1L)
    value <- trimws(substr(line, space_pos + 1L, nchar(line)))
    if (identical(value, "none")) {
      # 'none' marks a missing value, e.g. for a file without space information. It is kept as a string
      # so that a check can tell 'the field is absent' from 'the field could not be parsed'.
      result[[key]] <- value
    } else if (key == "custom") {
      # The name of a custom field is one token (DWMRI_b-value, DWMRI_gradient_0000, ...), except for the
      # built in 'measurement frame' field, whose name contains a space.
      if (startsWith(value, "measurement frame ")) {
        name <- "measurement frame"
        rest <- substr(value, nchar(name) + 2L, nchar(value))
      } else {
        tokens <- strsplit(value, "[[:space:]]+")[[1L]]
        name <- tokens[1L]
        rest <- paste(tokens[-1L], collapse = " ")
      }
      result$custom[[name]] <- suppressWarnings(as.numeric(strsplit(trimws(rest), "[[:space:]]+")[[1L]]))
    } else if (key %in% string_keys) {
      result[[key]] <- value
    } else if (key %in% int_keys) {
      result[[key]] <- as.integer(value)
    } else if (key %in% number_list_keys) {
      result[[key]] <- suppressWarnings(as.numeric(strsplit(value, "[[:space:]]+")[[1L]]))
    }
  }
  return(result)
}

tally <- function(status, checks, failures) {
  if (status == "OK") {
    checks <- checks + 1L
  } else if (status == "MISMATCH") {
    checks <- checks + 1L
    failures <- failures + 1L
  }
  return(list("checks" = checks, "failures" = failures))
}

report <- function(check_name, tool_label, status, detail = "") {
  cat(sprintf("   [%-30s] %-24s : %-8s %s\n", check_name, tool_label, status, detail))
  return(status)
}

#' Compare a vector of numbers, ignoring the difference between NA and NaN.
numerically_equal <- function(actual, expected, tolerance = 1e-9) {
  if (length(actual) != length(expected)) {
    return(FALSE)
  }
  both_na <- is.na(actual) & is.na(expected)
  return(all(both_na | (abs(actual - expected) <= tolerance)))
}

checks <- 0L
failures <- 0L
skipped <- 0L

if (!dir.exists(data_dir) || !dir.exists(dump_dir)) {
  cat(sprintf("SKIPPED: the test data directory '%s' or the dumps in '%s' do not exist.\n", data_dir, dump_dir))
  cat("Regenerate them with:\n")
  cat(sprintf("   python3 %s generate %s\n", file.path(repo_root, "dev_tools", "generate_nrrd_test_data.py"), data_dir))
  quit(status = 0L)
}

# Part 1: files with a dump from the reference implementations -------------------
cat("=== 1. Files read by pynrrd and ITK, compared with this package ===\n")

dump_files <- sort(list.files(dump_dir, pattern = "\\.expected\\.txt$"))
for (dump_file in dump_files) {
  file_name <- sub("\\.expected\\.txt$", "", dump_file)
  file_path <- file.path(data_dir, file_name)
  if (!file.exists(file_path)) {
    cat(sprintf("   [%-30s] %-24s : %-8s %s\n", file_name, "-", "MISMATCH", "the dump exists but the file does not"))
    failures <- failures + 1L
    checks <- checks + 1L
    next
  }
  expected <- read_nrrd_dump(file.path(dump_dir, dump_file))
  problems <- character(0L)

  header <- tryCatch(read.nrrd.header(file_path), error = function(e) e)
  data <- tryCatch(read.fs.volume.nrrd(file_path), error = function(e) e)

  if (inherits(header, "error")) {
    problems <- c(problems, sprintf("header reader failed: %s", conditionMessage(header)))
  } else if (inherits(data, "error")) {
    problems <- c(problems, sprintf("data reader failed: %s", conditionMessage(data)))
  } else {
    # The scalar data, as read by pynrrd.
    values <- as.vector(data)
    if (!identical(header$dimension, expected$dimension)) {
      problems <- c(problems, sprintf("dimension %d instead of %d", header$dimension, expected$dimension))
    } else if (!identical(as.integer(header$sizes), as.integer(expected$sizes))) {
      problems <- c(problems, sprintf("sizes %s instead of %s", paste(header$sizes, collapse = "x"), paste(expected$sizes, collapse = "x")))
    } else if (length(values) != expected$num_values) {
      problems <- c(problems, sprintf("%d values instead of %d", length(values), expected$num_values))
    } else if (!numerically_equal(values, expected$values)) {
      problems <- c(problems, sprintf("values differ, max difference %.3g", max(abs(values - expected$values))))
    }

    # The header fields that pynrrd reports.
    if (!identical(header$type, expected$type)) {
      problems <- c(problems, sprintf("type '%s' instead of '%s'", header$type, expected$type))
    }
    if (!identical(tolower(header$encoding), tolower(expected$encoding))) {
      problems <- c(problems, sprintf("encoding '%s' instead of '%s'", header$encoding, expected$encoding))
    }
    if (!identical(expected$endian, "none") && !identical(header$endian, expected$endian)) {
      problems <- c(problems, sprintf("endian '%s' instead of '%s'", header$endian, expected$endian))
    }
    if (!identical(expected$space, "none") && !identical(tolower(header$space), expected$space)) {
      problems <- c(problems, sprintf("space '%s' instead of '%s'", header$space, expected$space))
    }

    # The space information, as read by pynrrd.
    if (!identical(expected$space_directions, "none")) {
      expected_directions <- matrix(expected$space_directions, ncol = 3L, byrow = TRUE)
      if (is.null(header$space_directions)) {
        problems <- c(problems, "the space directions were not parsed")
      } else if (!numerically_equal(unname(header$space_directions), unname(expected_directions))) {
        problems <- c(problems, "the space directions differ")
      }
    }
    if (!identical(expected$space_origin, "none") && !is.null(expected$space_origin)) {
      if (is.null(header$space_origin)) {
        problems <- c(problems, "the space origin was not parsed")
      } else if (!numerically_equal(as.numeric(header$space_origin), expected$space_origin)) {
        problems <- c(problems, "the space origin differs")
      }
    }

    # The DWI metadata, as read by pynrrd.
    if (!is.null(expected$custom[["DWMRI_b-value"]])) {
      if (is.null(header$dwi)) {
        problems <- c(problems, "the DWI metadata was not parsed")
      } else {
        if (!numerically_equal(header$dwi$b_value, expected$custom[["DWMRI_b-value"]])) {
          problems <- c(problems, "the DWI b-value differs")
        }
        gradient_names <- grep("^DWMRI_gradient_", names(expected$custom), value = TRUE)
        expected_gradients <- t(vapply(gradient_names, function(name) expected$custom[[name]], numeric(3L)))
        if (is.null(header$dwi$bvec) || !numerically_equal(unname(header$dwi$bvec), unname(expected_gradients))) {
          problems <- c(problems, "the DWI gradients differ")
        }
        if (!is.null(header$dwi$measurement_frame) &&
            !numerically_equal(as.vector(t(header$dwi$measurement_frame)), as.numeric(expected$custom[["measurement frame"]]))) {
          problems <- c(problems, "the measurement frame differs")
        }
      }
    }

    # The geometry, as read by ITK. ITK cannot express a sheared basis (its image model has a rotation and a
    # spacing, no shear), so its direction cosines and spacings only describe the file when the basis of the
    # file can be written as such a product. Files with a representable basis have their voxel-to-RAS matrix
    # compared against the one computed from ITK's values; others are reported without being compared.
    itk_detail <- ""
    if (!is.null(expected$itk_origin) && !is.null(header$space_directions)) {
      itk_direction <- matrix(expected$itk_direction, ncol = 3L, byrow = TRUE)
      itk_spacing <- expected$itk_spacing
      itk_origin <- expected$itk_origin

      # ITK's geometry in RAS coordinates: the direction cosines scaled by the spacing, and the origin, with
      # the LPS to RAS sign flip of the first two axes.
      lps_to_ras <- diag(c(-1, -1, 1, 1))
      itk_vox2lps <- diag(4L)
      itk_vox2lps[1:3, 1:3] <- itk_direction %*% diag(itk_spacing)
      itk_vox2lps[1:3, 4L] <- itk_origin
      itk_vox2ras <- lps_to_ras %*% itk_vox2lps

      # The basis of the file, in RAS coordinates: the space directions are stored one vector per row, so
      # their columns are the basis vectors. Rows of non-space axes are dropped, and the sign flip of the
      # first two axes is applied for files whose space field is left-posterior-superior.
      space_rows <- which(rowSums(is.na(header$space_directions)) < ncol(header$space_directions))
      flip <- if (!is.null(header$space) && tolower(header$space) %in% c("left-posterior-superior", "lps")) c(-1, -1, 1) else c(1, 1, 1)
      file_basis <- t(header$space_directions[space_rows, , drop = FALSE]) %*% diag(flip)
      representable <- length(space_rows) == 3L &&
        numerically_equal(as.vector(itk_direction %*% diag(itk_spacing)), as.vector(file_basis))
      if (is.null(header$vox2ras_matrix)) {
        problems <- c(problems, "the voxel-to-RAS matrix is missing")
      } else if (numerically_equal(as.vector(unname(header$vox2ras_matrix)), as.vector(itk_vox2ras))) {
        itk_detail <- "geometry matches ITK"
      } else if (!representable) {
        itk_detail <- "ITK normalizes the sheared basis, geometry not compared"
      } else {
        problems <- c(problems, sprintf("the voxel-to-RAS matrix differs from ITK's geometry by %.3g",
                                        max(abs(unname(header$vox2ras_matrix) - itk_vox2ras))))
      }
    }

    # The matrix has to be consistent with the space directions and the origin that were read from the file.
    if (!is.null(header$vox2ras_matrix) && !is.null(header$space_directions)) {
      space_rows <- which(rowSums(is.na(header$space_directions)) < ncol(header$space_directions))
      flip <- if (!is.null(header$space) && tolower(header$space) %in% c("left-posterior-superior", "lps")) c(-1, -1, 1) else c(1, 1, 1)
      expected_matrix <- diag(4L)
      expected_matrix[1:3, 1:3] <- t(header$space_directions[space_rows, , drop = FALSE]) %*% diag(flip)
      origin <- if (is.null(header$space_origin)) c(0, 0, 0) else as.numeric(header$space_origin[1:3])
      expected_matrix[1:3, 4L] <- origin * flip
      if (!numerically_equal(as.vector(unname(header$vox2ras_matrix)), as.vector(expected_matrix))) {
        problems <- c(problems, "the voxel-to-RAS matrix does not match the space fields of the header")
      }
    }
  }

  status <- report(file_name, "pynrrd + ITK", if (length(problems) == 0L) "OK" else "MISMATCH",
                   if (length(problems) == 0L) {
                     sprintf("%s %s, %d values, %s", paste(if (!inherits(data, "error")) dim(data) else "?", collapse = "x"),
                             if (!inherits(header, "error")) header$type else "?", length(expected$values),
                             if (nzchar(itk_detail)) itk_detail else "no geometry in the file")
                   } else {
                     paste(problems, collapse = "; ")
                   })
  result <- tally(status, checks, failures)
  checks <- result$checks
  failures <- result$failures
}

# Part 2: the variants that pynrrd cannot read --------------------------------
cat("=== 2. Variants without a reference dump ===\n")

# The 'data file: LIST' mode: the header names two files that together hold the volume. The values have to be
# exactly those of the reference file, and the two data files have to be the halves of it.
list_file <- file.path(data_dir, "vol_datafile_list.nhdr")
reference_file <- file.path(data_dir, "vol_u8_raw.nrrd")
if (file.exists(list_file) && file.exists(reference_file)) {
  problems <- character(0L)
  list_values <- tryCatch(as.vector(read.fs.volume.nrrd(list_file)), error = function(e) e)
  reference_values <- as.vector(read.fs.volume.nrrd(reference_file))
  if (inherits(list_values, "error")) {
    problems <- c(problems, conditionMessage(list_values))
  } else if (!numerically_equal(list_values, reference_values)) {
    problems <- c(problems, "the values differ from the reference file")
  }
  header <- tryCatch(read.nrrd.header(list_file), error = function(e) e)
  if (inherits(header, "error")) {
    problems <- c(problems, conditionMessage(header))
  } else {
    if (length(header$data_files) != 2L) {
      problems <- c(problems, sprintf("%d data files instead of 2", length(header$data_files)))
    } else {
      # The two data files have to be the two halves of the data section of the reference file, in order.
      header_ref <- read.nrrd.header(reference_file)
      reference_bytes <- readBin(reference_file, "raw", n = file.size(reference_file))
      reference_data <- reference_bytes[(header_ref$data_offset + 1L):length(reference_bytes)]
      combined <- do.call(c, lapply(header$data_files, function(path) readBin(path, "raw", n = file.size(path))))
      if (!identical(combined, reference_data)) {
        problems <- c(problems, "the concatenated data files do not hold the data of the reference file")
      }
    }
  }
  status <- report("data file: LIST", "structural", if (length(problems) == 0L) "OK" else "MISMATCH",
                   if (length(problems) == 0L) sprintf("%d values from 2 files, identical to the reference", length(list_values)) else paste(problems, collapse = "; "))
} else {
  status <- "SKIPPED"
  skipped <- skipped + 1L
  report("data file: LIST", "structural", status, "test data missing")
}
result <- tally(status, checks, failures)
checks <- result$checks
failures <- result$failures

# A whole-file gzip-compressed NRRD file ('.nrrd.gz'). Neither pynrrd nor ITK read such a file, so it is
# compared against the uncompressed original, which does have a pynrrd dump.
gz_file <- file.path(data_dir, "vol_u8_raw.nrrd.gz")
if (file.exists(gz_file) && file.exists(reference_file)) {
  problems <- character(0L)
  gz_values <- tryCatch(as.vector(read.fs.volume.nrrd(gz_file)), error = function(e) e)
  reference_values <- as.vector(read.fs.volume.nrrd(reference_file))
  header_gz <- tryCatch(read.nrrd.header(gz_file), error = function(e) e)
  if (inherits(gz_values, "error")) {
    problems <- c(problems, conditionMessage(gz_values))
  } else if (!numerically_equal(gz_values, reference_values)) {
    problems <- c(problems, "the values differ from the uncompressed file")
  }
  if (!inherits(header_gz, "error")) {
    if (!isTRUE(header_gz$gzipped_file)) {
      problems <- c(problems, "the file was not detected as gzip-compressed")
    }
    if (!numerically_equal(as.numeric(header_gz$vox2ras_matrix), as.numeric(read.nrrd.header(reference_file)$vox2ras_matrix))) {
      problems <- c(problems, "the geometry differs from the uncompressed file")
    }
  }
  status <- report("whole-file gzip (.nrrd.gz)", "structural", if (length(problems) == 0L) "OK" else "MISMATCH",
                   if (length(problems) == 0L) sprintf("%d values, identical to the uncompressed file", length(gz_values)) else paste(problems, collapse = "; "))
} else {
  status <- "SKIPPED"
  skipped <- skipped + 1L
  report("whole-file gzip (.nrrd.gz)", "structural", status, "test data missing")
}
result <- tally(status, checks, failures)
checks <- result$checks
failures <- result$failures

# Part 3: cross-fixture consistency --------------------------------------------
cat("=== 3. Consistency of the variants of the same volume ===\n")

# All files with the 1..24 test volume have to read as the same values, no matter which header variant and
# which encoding they use. This is the check that catches a reader that gets one variant right and another
# one silently wrong.
base_volume_files <- c("vol_u8_raw.nrrd", "vol_u8_gzip.nrrd", "vol_u8_bzip2.nrrd", "vol_u8_ascii.nrrd",
                       "vol_u8_detached.nhdr", "vol_u8_detached_gz.nhdr", "vol_u8_raw.nrrd.gz",
                       "vol_datafile_list.nhdr", "vol_byteskip.nrrd", "vol_lineskip.nrrd",
                       "vol_byteskip_minus1.nrrd", "vol_gzip_byteskip_minus1.nrrd")
base_volume_files <- base_volume_files[file.exists(file.path(data_dir, base_volume_files))]

reference_values <- as.vector(read.fs.volume.nrrd(reference_file))
problems <- character(0L)
num_compared <- 0L
for (file_name in base_volume_files) {
  values <- tryCatch(as.vector(read.fs.volume.nrrd(file.path(data_dir, file_name))), error = function(e) e)
  num_compared <- num_compared + 1L
  if (inherits(values, "error")) {
    problems <- c(problems, sprintf("%s: %s", file_name, conditionMessage(values)))
  } else if (!numerically_equal(values, reference_values)) {
    problems <- c(problems, sprintf("%s: values differ", file_name))
  }
}
status <- report("12 variants of one volume", "this package", if (length(problems) == 0L) "OK" else "MISMATCH",
                 if (length(problems) == 0L) sprintf("%d files read identically", num_compared) else paste(problems, collapse = "; "))
result <- tally(status, checks, failures)
checks <- result$checks
failures <- result$failures

# Part 4: files without a dump are not silently ignored ------------------------
cat("=== 4. Coverage ===\n")
all_header_files <- sort(list.files(data_dir, pattern = "\\.(nrrd|nhdr)$"))
dumped_files <- sub("\\.expected\\.txt$", "", list.files(dump_dir, pattern = "\\.expected\\.txt$"))
uncovered <- setdiff(all_header_files, c(dumped_files, no_oracle_files))
status <- report(sprintf("%d header files", length(all_header_files)), "coverage",
                 if (length(uncovered) == 0L) "OK" else "MISMATCH",
                 if (length(uncovered) == 0L) {
                   sprintf("%d with a reference dump, %d structural", length(dumped_files), length(no_oracle_files))
                 } else {
                   sprintf("no dump and no structural check for: %s", paste(uncovered, collapse = ", "))
                 })
result <- tally(status, checks, failures)
checks <- result$checks
failures <- result$failures

cat(sprintf("\n%d checks performed, %d failures, %d skipped.\n", checks, failures, skipped))
if (failures > 0L) {
  stop("NRRD conversion checks failed.\n")
}
cat("All NRRD conversion checks passed.\n")
